### ISSUE TITLE
wrong affct row number in postgres-extended 

### ISSUE THREAD

**Issue by ZENOTME** [risinglightdb/sqllogictest-rs#142]
## How to reproduce:

```
//test.slt 
statement ok
create table t(v int)

statement count 1
insert into t values (1)

// run successfully
cargo run --bin sqllogictest -- -h localhost -p 4566 -u root -d dev -e postgres ./test.slt

// run fail
cargo run --bin sqllogictest -- -h localhost -p 4566 -u root -d dev -e postgres-extended ./test.slt

``````

## How to fix it 

https://github.com/risinglightdb/sqllogictest-rs/blob/cb3c99dc61be4ae65fb3391a2028209a7d015f0d/sqllogictest-bin/src/engines/postgres_extended.rs#L237
change to 
```
let cnt = self.client.execute(sql, &[]).await?; 
return Ok(DBOutput::StatementComplete(cnt));
```

**Comment by skyzh** [comment]
This is still not completely given #141 only correctly solves the case for simple protocol. Extended protocol still uses a simple match for DML. One possible solution is to have a new kind of stream which returns both query set and affected rows by modifying rust-postgres.

https://github.com/sfackler/rust-postgres/blob/f4d8d603f1b9d3edd9b93889465f3db5bba0fd40/tokio-postgres/src/query.rs#L210-L228

**Comment by skyzh** [comment]
Also we can consider not to differentiate `DBOutput::Rows` and `DBOutput::StatementComplete`.

**Comment by ZENOTME** [comment]
> One possible solution is to have a new kind of stream which returns both query set and affected rows by modifying rust-postgres.

Agree with this solution. So I think we should fork rust-postgres in risinglightdb?

**Comment by skyzh** [comment]
Yes, and I would also prefer making this change into the upstream.

**Comment by ZENOTME** [comment]
> Also we can consider not to differentiate DBOutput::Rows and DBOutput::StatementComplete.

If we don't differentiate DBOutput::Rows and DBOutput::StatementComplete, it may cause the confused problem like:
```
// case 1
statement count 1
----
select 1;

// case 2
statement count 1
----
select 2;

// case 3
statement count 1
----
insert into t values (1)
``````
The result of both case will be same but their semantics is different. 
For our current implementation, case 1 and case 2 will be passed because we tolerate the miss type match.
https://github.com/risinglightdb/sqllogictest-rs/blob/f4e2121da6164acfdfcfb3858d8f4bee9891d0a7/sqllogictest/src/runner.rs#L576

But if we mix DBOutput::Rows and DBOutput::StatementComplete, there maybe a scene where case 1 passed but case 2 failed. I think this will cause confused.🤔

**Comment by ZENOTME** [comment]
> Yes, and I would also prefer making this change into the upstream.

I would like to make this change. We fork a version and apply the modifcation first. And then I will try to making this change into the upstream.

**Comment by skyzh** [comment]
I'm gonna do that :)
