### ISSUE TITLE
Make Result an associated type for DB

### ISSUE THREAD

**Issue by Xuanwo** [risinglightdb/sqllogictest-rs#16]
By the way, can we go a step further? e.g., add a `Result` associated type for `DB`, so that we can pass any type apart from `String` as query result. (Not needed in this PR)

Also, I would recommend adding an example for validator in `examples` folder.

_Originally posted by @skyzh in https://github.com/singularity-data/sqllogictest-rs/pull/15#pullrequestreview-857813525_

**Comment by xxchan** [comment]
We are using `Vec<Vec<String>>` now. There seem to be no need to use an associated type.
