### ISSUE TITLE
ci: add semver check in CI

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/sqllogictest-rs#167]
I feel I cannot catch all API changes during my review, and it would be a good idea to use a tool in this case 🤪

**Comment by skyzh** [comment]
Okay we did accidentally break something. We will need to bump to 0.13 instead of 0.12.1.

**Comment by melgenek** [comment]
> Okay we did accidentally break something. We will need to bump to 0.13 instead of 0.12.1.

I am sorry that I didn't mention a new function parameter explicitly. I wasn't sure how strict the releases in this library are in terms of api compatibility.


Thank you for taking care of this issue!

**Comment by skyzh** [comment]
No worries! I think we also didn't take this seriously for a long time...
