### ISSUE TITLE
`statement error` test should fail when expected error did not occur

### ISSUE THREAD

**Issue by xiangjinwu** [risinglightdb/sqllogictest-rs#178]
Reproduce:
With PostgreSQL running on port 5432,
```
sqllogictest -p 5432 -d test -u $USER <(echo $'statement error\nselect 1;')
```

Expected:
`[FAILED]`: query is expected to error but did not

Actual:
`[OK]`

Practical usage:
```
statement error
select power(-1, 0.5);
```

**Comment by xxchan** [comment]
I can reproduce. BTW, `query error` is correct.

<img width="727" alt="image" src="https://github.com/risinglightdb/sqllogictest-rs/assets/37948597/47ad9191-fd32-4d47-ae35-a7c15663e21f">

**Comment by xiangjinwu** [comment]
Thank you. Seems `query error` is an undocumented extension?
