### ISSUE TITLE
A finally-statement-like code block to clean up things

### ISSUE THREAD

**Issue by lmatz** [risinglightdb/sqllogictest-rs#18]
Sometimes, the test files are maintained by different people and they may use the same name for a table or view. This is reasonable as we may view these test files as independent units.

When some test case in one test file failed, `sqllogictest` proceeds to execute another test file. Without dropping all of the tables and views, it can cause `table exists` failure in the coming tests.

Therefore, this issue proposes that we may have a `finally statement` like mechanism to clean up things. Statement in the `finally` code block would be always executed at last.

Is this mechanism worth implementing? Not necessarily design and implement it in this way, though.

**Comment by wangrunji0408** [comment]
Sounds like a useful feature! For the command name, what about `defer` like go?

Another solution to this problem is to create a temporary database for each file, and drop it on exit. I think this would be a simpler way?

**Comment by lmatz** [comment]
> Another solution to this problem is to create a temporary database for each file, and drop it on exit. I think this would be a simpler way?

Indeed!

**Comment by lmatz** [comment]
On second thought,
using `create a temporary database` may not handle tests that specifically test statements like `create database XXX`, `SET database TO XXX`. But these also seem to be corner cases. Doubt there will be many cases like this.

Torn between these two choices. 🤣

**Comment by lmatz** [comment]
`create a temporary database` for each test case is adopted eventually.
