### ISSUE TITLE
Bug: sqllogictest pass unexpectedly

### ISSUE THREAD

**Issue by JackTan25** [risinglightdb/sqllogictest-rs#181]
statement error 1090
create table t(a int);

as we know, this statement will be ok, but I set it as error 1090 by design. Unexpectedly, this test passes, it's not right. please fix this one.

**Comment by xxchan** [comment]
duplicate with https://github.com/risinglightdb/sqllogictest-rs/issues/178

**Comment by xxchan** [comment]
> as we know, this statement will be ok

No, we don't know how you used it. Please be more specific and provide a reproduce.

> please fix this one.

Please be aware that we don't guarantee to fix every bug timely. But we will happily review your PR :)
