### ISSUE TITLE
Should we run `semver` test on release instead of each PR?

### ISSUE THREAD

**Issue by BugenZhao** [risinglightdb/sqllogictest-rs#195]
Currently, we'll run `cargo semver-checks` to prevent API changes without bumping the major version (or minor version under `0.x`). Essentially, this requires each PR with breaking changes to bump the major version in place.

Imagine that we have 10 PRs with breaking changes merged one day and we intend to publish them together. Then we have to bump the version 10 times under current restrictions. 😕 Also, I don't think it's a good idea to bump the version in place. A separate PR (or commit) can be much clearer.

So I'm wondering whether we should only run `semver` test on release (publish) instead?

**Comment by xxchan** [comment]
sure

**Comment by skyzh** [comment]
IIRC semver compares with latest version on crates.io instead of main? Therefore only the first PR needs to bump version 🤪

**Comment by skyzh** [comment]
But I'm also open to do semver check on release.

**Comment by xxchan** [comment]
> IIRC semver compares with latest version on crates.io instead of main? Therefore only the first PR needs to bump version

Yes, since we don't have many PRs and release frequently, I also think it's OK to bump version in PR directly. It's a problem for projects that don't release frequently.
