### ISSUE TITLE
Abort the entire test file

### ISSUE THREAD

**Issue by lmatz** [risinglightdb/sqllogictest-rs#20]
Right now, we put all of the tpch test cases (q1.slt.part, q3.slt.part......) in one test file(tpch.slt) as we want to share all the common tables from tpch.

However, a failure in q1.slt.part would abort the whole test file. But q3 has nothing to do Q1 and checking its results(if wrong) would save an extra run.

Should we abort in a finer granularity, i.e. slt.part level? Or we should introduce some primitives for specifying different dependencies between test cases?

**Comment by liurenjie1024** [comment]
Another reason we should not skip remaining parts is cleaning up. For example, in our tpch test, the last part is dropping tables, which should not be skipped so that we can rerun the test script without restart.

**Comment by xxchan** [comment]
Currently we can use `-j1` to isolate different `.slt` tests in case cleaning cannot be done in a failed test. 

As for isolating `include *.slt.part`, it's not intended usage for the current `include` semantics. See also https://github.com/singularity-data/risingwave/issues/3629
