### ISSUE TITLE
panic at unreachable if it's not installed with `--locked`

### ISSUE THREAD

**Issue by kemingy** [risinglightdb/sqllogictest-rs#232]
Following the README instruction: `cargo install sqllogictest-bin` will update the `tokio-postgres` from **0.7.10** to **0.7.12**, which has a potential breaking change that will cause a panic in https://github.com/risinglightdb/sqllogictest-rs/blob/a6bbfdbfeeaf2b08fdbe0158dcf73cb3312c7bd7/sqllogictest-engines/src/postgres/simple.rs#L46

This could be solved by `cargo install sqllogictest-bin --locked`, though some crates are already yanked.

**Comment by skyzh** [comment]
fixed with https://github.com/risinglightdb/sqllogictest-rs/pull/233 :)
