### ISSUE TITLE
Proposal: support syntax "SET DEFAULT [GLOBAL] $SortMode"

### ISSUE THREAD

**Issue by MrCroxx** [risinglightdb/sqllogictest-rs#24]
In distributed environment, the order of query result set is uncertain, which is also not required in SQL without "ORDER BY".

To simplify the test script, we can support syntax like `SET DEFAULT [GLOBAL] $SortMode` to set the default sort mode required by `query` statement in the current file or all files, instead of specify sort mode after each. `query` statement.

**Comment by fuyufjh** [comment]
-1. It's good enough to return a result set with uncertain ordering.

**Comment by fuyufjh** [comment]
Can we add an mode to compare result set without ordering?

**Comment by fuyufjh** [comment]
BTW, it's bad to use a `SET DEFAULT...` syntax because `SET` command is usually a command for database.

**Comment by MrCroxx** [comment]
> Can we add an option to compare the result set without ordering?

We already have. But it's not the default config.

**Comment by MrCroxx** [comment]
@fuyufjh Do you prefer set `RowSort` as default or keep the current config and introduce a syntax to set the sort mode, 0.0 .

**Comment by fuyufjh** [comment]
> @fuyufjh Do you prefer set RowSort as default or keep the current config and introduce a syntax to set the sort mode, 0.0 .

Both are okay for me. But if we want others to use our `sqllogictest-rs`, Prefer the later one ("introduce a syntax to set the sort mode")

**Comment by skyzh** [comment]
Yes, I would prefer to use some control statement. Currently, we have:

```
statement ok
xxxx
```

... and we can have

```
+control default rowsort
```
