### ISSUE TITLE
feat(release): support Linux ARM64

### ISSUE THREAD

**Issue by kemingy** [risinglightdb/sqllogictest-rs#240]
- https://github.blog/changelog/2024-09-03-github-actions-arm64-linux-and-windows-runners-are-now-generally-available/

GitHub supports Linux ARM64 runner for Team and Enterprise Cloud plans.

Ubicloud also has a [1,250 minutes-free/month](https://www.ubicloud.com/docs/about/pricing) that supports Linux ARM64. I guess that's enough for the release action.

Do you plan to add this one?

**Comment by xxchan** [comment]
added in #241  by @usamoi 

and 0.25.0 released https://github.com/risinglightdb/sqllogictest-rs/releases/tag/v0.25.0
