### ISSUE TITLE
generate test result using actual output of a run

### ISSUE THREAD

**Issue by leiysky** [risinglightdb/sqllogictest-rs#43]
For example, given a test statement:
```
query I
select a from t;
```

Is is possible to generate a test file as:
```
query I
select a from t;
----
1
2
3
```

**Comment by leiysky** [comment]
cc @skyzh

**Comment by skyzh** [comment]
That's interesting! I think we can do this in sqllogictest.

https://github.com/risinglightdb/sqllogictest-rs/blob/main/src/main.rs

Currently, main.rs uses sqllogictest lib to parse and run the tests while offering a fancy cli. I think we can leverage sqllogictest library to generate test result.

**Comment by leiysky** [comment]
@skyzh The official sqllogictest is able to take a **prototype** test file as input, and produce a complete test file with following command:
```shell
sqllogictest -odbc DSN=mysqlslt MySQL prototype.test >full.test
```

Maybe we can just follow this.

**Comment by xxchan** [comment]
`include` makes it tricky 🤡
