### ISSUE TITLE
Print (empty) for empty strings

### ISSUE THREAD

**Issue by kwannoel** [risinglightdb/sqllogictest-rs#46]
Currently sqllogictest returns empty string rendered as is:
```
query T
select concat(NULL, NULL);
----

```

It should render it as:
```
query T
select concat(NULL, NULL);
----
(empty)
```

As per `sqllogictest` docs - https://www.sqlite.org/sqllogictest/doc/trunk/about.wiki:
>  Empty strings are rendered as "(empty)"

**Comment by skyzh** [comment]
I think this is controlled by the actual database implementation.

https://github.com/risinglightdb/sqllogictest-rs/blob/f41a7bfc3c79160a644a1a16eca91effe97d758a/examples/basic.rs#L19-L33

In sqllogictest's perspective, it simply compares and verifies a string.

**Comment by skyzh** [comment]
Oh maybe you're referring to the sqllogictest binary. In this case,

https://github.com/risinglightdb/sqllogictest-rs/blob/f41a7bfc3c79160a644a1a16eca91effe97d758a/src/main.rs#L372-L375

It is true that we didn't write anything for an empty string 🤣

**Comment by kwannoel** [comment]
> Oh maybe you're referring to the sqllogictest binary. In this case,
> 
> [sqllogictest-rs/src/main.rs](https://github.com/risinglightdb/sqllogictest-rs/blob/f41a7bfc3c79160a644a1a16eca91effe97d758a/src/main.rs#L372-L375)
> 
> Lines 372 to 375 in [f41a7bf](https://github.com/risinglightdb/sqllogictest-rs/commit/f41a7bfc3c79160a644a1a16eca91effe97d758a)
>  match row.get(i) { 
>      Some(v) => write!(output, "{}", v).unwrap(), 
>      None => write!(output, "NULL").unwrap(), 
>  } 
> 
> It is true that we didn't write anything for an empty string :rofl: 

Yes, that's what I was referring to, I think the sqllogictest binary needs to specially handle empty strings, similar to what it does for the `NULL` case above :rofl:
