### ISSUE TITLE
error: an error in basic.slt?

### ISSUE THREAD

**Issue by ZENOTME** [risinglightdb/sqllogictest-rs#62]
https://github.com/risinglightdb/sqllogictest-rs/blob/3698ea5be9c61b5d36c1cc702d17e4b450ab2295/examples/basic.slt#L9

example_basic should be t? or t should be example_basic?

**Comment by skyzh** [comment]
This is made to be complement with https://github.com/risinglightdb/sqllogictest-rs/blob/main/examples/basic.rs, which is not a real database system.
