### ISSUE TITLE
Support extended query mode

### ISSUE THREAD

**Issue by ZENOTME** [risinglightdb/sqllogictest-rs#64]
For now, sqllogictest only support simple query mode. For introducing e2e test of extend query mode in risingwave, we should add extend query in the sqllogictest and using a opt '--extend' to choice 'simple query' or 'extended query'.

**Comment by xxchan** [comment]
I think this may be beyond the scope of sqllogictest? How do you want to test it?

**Comment by ZENOTME** [comment]
Because now the CI in risingwave is use the bin of sqllogictest to test, so I guess we can add the extended query in the bin? I create the PR #65.
