### ISSUE TITLE
refactor: moving binary to sqllogictest-bin

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/sqllogictest-rs#66]
It's becoming more and more complex, so it would be good to have a separate crate.

cc @xxchan do you want to work on this? If so feel free to assign yourself. Otherwise I'll do the refactor maybe this month.

**Comment by wangrunji0408** [comment]
Or consider moving some features into the library? Recently I'm working on deterministic e2e testing, where sqllogictest is used as a library.

**Comment by xxchan** [comment]
🤔 I'm wondering:
- Whether drivers live in lib or bin crate
- Will we bump versions for them together in the future


> Or consider moving some features into the library? Recently I'm working on deterministic e2e testing, where sqllogictest is used as a library.

How will moving binary affect your requirement? 🤔

**Comment by xxchan** [comment]
I've drafted a PR https://github.com/risinglightdb/sqllogictest-rs/pull/67, we can discuss there

**Comment by wangrunji0408** [comment]
> How will moving binary affect your requirement? 🤔

It won't affect. The current refactor looks cool.
My proposal is to move some codes from `sqllogictest-bin/lib.rs` to `sqllogictest/runner.rs`, such as parallel running and printing progress.
