### ISSUE TITLE
Use per file session for serial mode

### ISSUE THREAD

**Issue by xxchan** [risinglightdb/sqllogictest-rs#85]
If we set a session variable in `a.slt`, and then it will be still be set in `b.slt`. I think this is very error-prone, although we can do clean-up for session variable like for tables.

`include` problem is related but different: Currenly `include`'s semantic is just copy-paste. Isolation for `include` subtests is another problem, as in #55, #81. This issue says different `slt`s should have isolated sessions.

If so, would serial mode the same as `-j1`? No, `-j1` will have isolated DBs. Serial mode isolates sessions, but do not isolates DBs, so clean-up tables is still needed

**Comment by fuyufjh** [comment]
> include's semantic is just copy-paste.

That sounds intuitive to me (and other users, I think). I don't think you need do anything else for it.
